# Use Flutter SDK image
FROM ghcr.io/cirruslabs/flutter:latest

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Get dependencies
RUN flutter pub get

# Build release (APK)
RUN flutter build apk --release

# What this container does by default
CMD ["bash"]